Pass CPU and Memory config to minikube to ensure better stability
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

diff --git a/.github/actions/setup-minikube/action.yml b/.github/actions/setup-minikube/action.yml
--- a/.github/actions/setup-minikube/action.yml
+++ b/.github/actions/setup-minikube/action.yml
@@ -9,21 +9,82 @@ inputs:
   minikubeVersion:
     description: "Minikube version to install"
     required: false
-    default: "v1.33.1"
+    default: "v1.35.0"
   architecture:
     description: "Architecture"
     required: false
     default: "amd64"
+  cpu:
+    description: "CPU configuration for Minikube"
+    required: false
+    default: "2"
+  memory:
+    description: "Memory configuration for Minikube"
+    required: false
+    default: "6000"
+  retries:
+    description: "Number of retries"
+    required: false
+    default: "3"
+  registry:
+    description: "Image used for Minikube Registry"
+    required: false
+    default: mirror.gcr.io/registry:2.8.3
 
 runs:
   using: "composite"
   steps:
+    - name: Cache registry Docker image
+      id: cache-registry
+      uses: actions/cache@v4
+      with:
+        path: /tmp/registry-image.tar
+        key: minikube-registry-image
+
+    - name: Load registry Docker image from cache
+      if: steps.cache-registry.outputs.cache-hit == 'true'
+      shell: bash
+      run: |
+        docker load -i /tmp/registry-image.tar
+
+    - name: Pull and save registry Docker image if cache miss
+      if: steps.cache-registry.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        docker pull ${{ inputs.registry }}
+        docker save ${{ inputs.registry }} -o /tmp/registry-image.tar
+
     - name: Setup Minikube
       shell: bash
       run: |
-        .azure/scripts/setup-kubernetes.sh "${{ inputs.architecture }}"
+        COUNT=0
+        until [ $COUNT -ge $RETRIES ]
+        do
+          if .azure/scripts/setup-kubernetes.sh "${{ inputs.architecture }}"; then
+            echo "Minikube setup succeeded."
+            break
+          fi
+          COUNT=$((COUNT+1))
+          echo "Retry $COUNT/$RETRIES failed. Deleting Minikube and retrying in 10 seconds..."
+          minikube delete
+          sleep 10
+        done
+
+        if [ $COUNT -eq $RETRIES ]; then
+          echo "Minikube setup failed after $RETRIES attempts."
+          exit 1
+        fi
+
       env:
         TEST_CLUSTER: minikube
         TEST_KUBECTL_VERSION: ${{ inputs.kubectlVersion }}
         TEST_MINIKUBE_VERSION: ${{ inputs.minikubeVersion }}
-        REGISTRY_IMAGE: mirror.gcr.io/registry:latest
+        REGISTRY_IMAGE: mirror.gcr.io/registry:2.8.3
+        MINIKUBE_MEMORY: ${{ inputs.memory }}
+        MINIKUBE_CPU: ${{ inputs.cpu }}
+        RETRIES: ${{ inputs.retries }}
+
+    - name: DEBUG - check running containers
+      shell: bash
+      run: |
+        docker ps -a
