Switch to VMs as runners for building and running tests
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

diff --git a/.github/actions/containers-load/action.yml b/.github/actions/containers-load/action.yml
--- a/.github/actions/containers-load/action.yml
+++ b/.github/actions/containers-load/action.yml
@@ -32,42 +32,42 @@ runs:
       if: ${{ contains(inputs.useMinikube, 'true') }}
       run: |
         eval $(minikube docker-env)
-        make docker_load docker_tag docker_delete_archive
+        make docker_load docker_tag docker_push docker_delete_archive
         
         docker images -a
-        
-        RETRIES=3
-        COUNT=0
-        until [ $COUNT -ge $RETRIES ]
-        do
-          if make docker_e2e; then
-            echo "Push succeeded"
-            break
-          fi
-          COUNT=$((COUNT+1))
-          echo "Retry $COUNT/$RETRIES failed. Retrying in 10 seconds..."
-          sleep 10
-          echo "Pods"
-          kubectl get po -n kube-system
-          echo "Kube proxy log"
-          kubectl logs daemonset/kube-proxy -n kube-system
-          docker ps -a
-          docker images -a
-          docker logs kind-registry
-        done
-
-        if [ $COUNT -eq $RETRIES ]; then
-          echo "Push failed after $RETRIES attempts."
-          exit 1
-        fi
-        
-        echo "Pods"
-        kubectl get po -n kube-system
-        echo "Kube proxy log"
-        kubectl logs daemonset/kube-proxy -n kube-system
-        docker ps -a
-        docker logs kind-registry
-        docker images -a
+#
+#        RETRIES=3
+#        COUNT=0
+#        until [ $COUNT -ge $RETRIES ]
+#        do
+#          if make docker_e2e; then
+#            echo "Push succeeded"
+#            break
+#          fi
+#          COUNT=$((COUNT+1))
+#          echo "Retry $COUNT/$RETRIES failed. Retrying in 10 seconds..."
+#          sleep 10
+#          echo "Pods"
+#          kubectl get po -n kube-system
+#          echo "Kube proxy log"
+#          kubectl logs daemonset/kube-proxy -n kube-system
+#          docker ps -a
+#          docker images -a
+#          docker logs kind-registry
+#        done
+#
+#        if [ $COUNT -eq $RETRIES ]; then
+#          echo "Push failed after $RETRIES attempts."
+#          exit 1
+#        fi
+#
+#        echo "Pods"
+#        kubectl get po -n kube-system
+#        echo "Kube proxy log"
+#        kubectl logs daemonset/kube-proxy -n kube-system
+#        docker ps -a
+#        docker logs kind-registry
+#        docker images -a
 
       env:
         DOCKER_ARCHITECTURE: ${{ inputs.architecture }}
